name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'  # This will run every day at 9:00 AM UTC

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Make a dummy change and commit
        run: |
          echo "Update file $(date)" >> daily-commit.txt
          git add daily-commit.txt
          git commit -m "Daily commit at $(date)" --author="Daily Commit <23f3003879@ds.study.iitm.ac.in>"
          git push
