name: Daily Commit

on:
  schedule:
    - cron: '42 12 * * *'  # This will run at 12:42 PM UTC (which is 6:12 PM IST)
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Set Git configuration
        run: |
          git config --global user.email "23f3003879@ds.study.iitm.ac.in"
          git config --global user.name "Daily Commit"
      
      - name: Make a dummy change and commit
        run: |
          echo "Update file $(date)" >> daily-commit.txt
          git add daily-commit.txt
          git commit -m "Daily commit at $(date)" --author="Daily Commit <23f3003879@ds.study.iitm.ac.in>"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/23f3003879/tds_ga4.git
